name: "Setup Continuous Integration"
description: "Cache Dependencies"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "yarn"

    - name: Cache NPM Dependencies
      uses: actions/cache@v3
      id: cache-primes
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}

    - name: Install Dependencies
      run: yarn install 
      shell: bash