/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as org_membership from "../org_membership.js";
import type * as project from "../project.js";
import type * as projects from "../projects.js";
import type * as team from "../team.js";
import type * as user from "../user.js";
import type * as work_items from "../work_items.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  org_membership: typeof org_membership;
  project: typeof project;
  projects: typeof projects;
  team: typeof team;
  user: typeof user;
  work_items: typeof work_items;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
