name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: 20.11.0

jobs:
  linting:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Continuous integration
        uses: ./.github/actions/ci-setup

      - name: Lint Application
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Continuous Integration
        uses: ./.github/actions/ci-setup

      - name: Build Application
        env:
          NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
          CONVEX_DEPLOYMENT: ${{ secrets.CONVEX_DEPLOYMENT }}
        run: yarn build