name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: 20.11.0

jobs:
  linting:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Continuous integration
        uses: ./.github/actions/ci-setup

      - name: Lint Application
        run: yarn lint

  type-check:
    name: Apps/Web Types
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Continuous Integration
        uses: ./.github/actions/ci-setup

      - name: Check Application Types
        run: yarn type-check

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Continuous Integration
        uses: ./.github/actions/ci-setup

      - name: Copy Env File
        run: cp .env.example .env

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@v1.10.0
        with:
          mongodb-username: username
          mongodb-password: password
          mongodb-db: test

      - name: Build Application
        run: yarn build